modLoader="javafml" 
loaderVersion="[27,)"
issueTrackerURL="http:/github.com/CraftedMods/jei-lotr/issues" 
[[mods]] 
modId="jeilotr" 
version="1.3.0-BETA" 
displayName="JEI LOTR" 
updateJSONURL="https://raw.githubusercontent.com/CraftedMods/jei-lotr/master/versions.json" 
displayURL="http://github.com/CraftedMods/jei-lotr" 
credits="Malvegil, Mevans (LOTR Mod), mezz (JEI), the FML and Forge team, Mojang" 
authors="Malvegil a.k.a. CraftedMods, Crafted_Mods or The Ranger Malvegil" 

description='''
A JEI-Plugin for the "The Lord of the Rings" Minecraft Mod.
'''
[[dependencies.jeilotr]] 
    # the modid of the dependency
    modId="forge" 
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true 
    # The version range of the dependency
    versionRange="[31,)" 
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.jeilotr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeilotr]]
    modId="lotr"
    mandatory=true
    versionRange="[Renewed-1.7.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.jeilotr]]
    modId="jei"
    mandatory=true
    versionRange="[6.0.3.15,)"
    ordering="NONE"
    side="BOTH"
